### ISSUE TITLE
bootstrap for raspberrypi 4B?

### ISSUE THREAD

**Issue by jimerickson** [fhs/go-plan9-binaries#1]
could we get a boostrap for raspberrypi 4B? that would be arm8. or is there another way to boostrap the raspberrypi 4B? i need these binaries badly!

**Comment by fhs** [comment]
I'm not that familiar with arm. `GOARM=8` is not valid. Do the `GOARM=7` binaries not work in a 32-bit plan9 install? Or are you running 64-bit plan9 (which requires `GOARCH=arm64`)?

**Comment by jimerickson** [comment]
that is correct the 32bit binaries won't work on a 64bit install. at least not for me.

**Comment by fhs** [comment]
arm64 is not supported. However, you can try out the WIP arm64 port: https://github.com/golang/go/issues/57540

**Comment by jimerickson** [comment]
thanks much!
